apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: user-postgres
  labels:
    app: user-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-postgres
  template:
    metadata:
      labels:
        app: user-postgres
    spec:
      containers:
        - name: user-postgres
          image: mauricio1998/user-postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432