apiVersion: v1
kind: Service
metadata:
  name: user-postgres
  labels:
    app: user-postgres
spec:
  selector:
    app: user-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP