apiVersion: v1
data:
  config.yaml: |
    customerServer:
      port: 8081
    userServer:
      port: 8082
    token:
      key: "dnVJWGFPSzRPcEpXQTl5U1gxVVRwSVdzaFhQcFA2bmVHS0dBNzI0RmF1WQ=="
    port: 8083
    db:
      connectionString: host=user-postgres.fiap.svc.cluster.local port=5432 dbname=fiap_tech_challenge user=postgres password=1234 sslmode=disable
kind: ConfigMap
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: fiap