apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fiap
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: payment-service
          image: mauricio1998/user-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          volumeMounts:
            - name: user-service
              subPath: config.yaml
              mountPath: /app/config.yaml
      volumes:
        - name: user-service
          configMap:
            name: "user-service"