apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 8083
      targetPort: 8083
      name: rest
    - port: 8082
      targetPort: 8082
      name: user-grpc
    - port: 8081
      targetPort: 8081
      name: customer-grpc
  type: ClusterIP