apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: user-service-

commonAnnotations:
  team: team4

labels:
- includeSelectors: true
  pairs:
    app: user-service

resources:
- github.com/mauriciodm1998/kustomization/base?ref=v1.0.4